#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAPI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AppCentral")]
	public partial class AppCentralDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AppCentralDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppCentralDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppCentralDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppCentralDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCreaTransaction")]
		public int spAVSCreaTransaction(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipToID", DbType="Int")] System.Nullable<int> shipToID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionNumber", DbType="Int")] System.Nullable<int> transactionNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BatchNumber", DbType="Int")] System.Nullable<int> batchNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Time", DbType="NVarChar(25)")] string time, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="NVarChar(13)")] string customerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashierID", DbType="Int")] System.Nullable<int> cashierID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Money")] System.Nullable<decimal> total, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesTax", DbType="Money")] System.Nullable<decimal> salesTax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(255)")] string comment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceNumber", DbType="NVarChar(50)")] string referenceNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChannelType", DbType="Int")] System.Nullable<int> channelType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecallID", DbType="Int")] System.Nullable<int> recallID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecallType", DbType="Int")] System.Nullable<int> recallType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExchangeID", DbType="Int")] System.Nullable<int> exchangeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerFullName", DbType="NVarChar(50)")] string customerFullName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerAccountNumber", DbType="NVarChar(50)")] string customerAccountNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubTotal", DbType="Money")] System.Nullable<decimal> subTotal, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descuentos", DbType="Money")] System.Nullable<decimal> descuentos, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesRepID", DbType="Int")] System.Nullable<int> salesRepID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), shipToID, storeID, transactionNumber, batchNumber, time, customerID, cashierID, total, salesTax, comment, referenceNumber, status, channelType, recallID, recallType, exchangeID, customerFullName, customerAccountNumber, subTotal, descuentos, salesRepID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCreaTransactionEntry")]
		public int spAVSCreaTransactionEntry(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Commission", DbType="Money")] System.Nullable<decimal> commission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cost", DbType="Money")] System.Nullable<decimal> cost, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FullPrice", DbType="Money")] System.Nullable<decimal> fullPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionNumber", DbType="Int")] System.Nullable<int> transactionNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemID", DbType="Int")] System.Nullable<int> itemID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Money")] System.Nullable<decimal> price, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PriceSource", DbType="Money")] System.Nullable<decimal> priceSource, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantity", DbType="Float")] System.Nullable<double> quantity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesRepID", DbType="Int")] System.Nullable<int> salesRepID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Taxable", DbType="Bit")] System.Nullable<bool> taxable, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DetailID", DbType="Int")] System.Nullable<int> detailID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(255)")] string comment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountReasonCodeID", DbType="Int")] System.Nullable<int> discountReasonCodeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReturnReasonCodeID", DbType="Int")] System.Nullable<int> returnReasonCodeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaxChangeReasonCodeID", DbType="Int")] System.Nullable<int> taxChangeReasonCodeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesTax", DbType="Money")] System.Nullable<decimal> salesTax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuantityDiscountID", DbType="Int")] System.Nullable<int> quantityDiscountID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemType", DbType="Int")] System.Nullable<int> itemType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ComputedQuantity", DbType="Float")] System.Nullable<double> computedQuantity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionTime", DbType="VarChar(30)")] string transactionTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsAddMoney", DbType="Bit")] System.Nullable<bool> isAddMoney, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VoucherID", DbType="Int")] System.Nullable<int> voucherID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioEditado", DbType="Money")] System.Nullable<decimal> precioEditado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, commission, cost, fullPrice, storeID, transactionNumber, itemID, price, priceSource, quantity, salesRepID, taxable, detailID, comment, discountReasonCodeID, returnReasonCodeID, taxChangeReasonCodeID, salesTax, quantityDiscountID, itemType, computedQuantity, transactionTime, isAddMoney, voucherID, precioEditado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCreaLocation")]
		public int spAVSCreaLocation([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RutaID", DbType="NVarChar(50)")] string rutaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(255)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Latitud", DbType="Float")] System.Nullable<double> latitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Longitud", DbType="Float")] System.Nullable<double> longitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="Int")] System.Nullable<int> tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rutaID, customerID, nombre, descripcion, latitud, longitud, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSGetLocationsbyCriteria")]
		public ISingleResult<spAVSGetLocationsbyCriteriaResult> spAVSGetLocationsbyCriteria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criteria", DbType="Int")] System.Nullable<int> criteria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteria);
			return ((ISingleResult<spAVSGetLocationsbyCriteriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCreaRoute")]
		public int spAVSCreaRoute([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceNumber", DbType="NVarChar(50)")] string referenceNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashierID", DbType="Int")] System.Nullable<int> cashierID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), storeID, referenceNumber, nombre, cashierID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSGetRoutesbyCriteria")]
		public ISingleResult<spAVSGetRoutesbyCriteriaResult> spAVSGetRoutesbyCriteria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criteria", DbType="NVarChar(50)")] string criteria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteria);
			return ((ISingleResult<spAVSGetRoutesbyCriteriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCreaOrden")]
		public int spAVSCreaOrden(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Time", DbType="NVarChar(30)")] string time, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tax", DbType="Money")] System.Nullable<decimal> tax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Money")] System.Nullable<decimal> total, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastUpdated", DbType="NVarChar(30)")] string lastUpdated, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpirationOrDueDate", DbType="NVarChar(30)")] string expirationOrDueDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceNumber", DbType="NVarChar(50)")] string referenceNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerFullName", DbType="NVarChar(50)")] string customerFullName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerAccountNumber", DbType="NVarChar(50)")] string customerAccountNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoEnviado", DbType="Bit")] System.Nullable<bool> correoEnviado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubTotal", DbType="Money")] System.Nullable<decimal> subTotal, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descuentos", DbType="Money")] System.Nullable<decimal> descuentos, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isProforma, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Closed", DbType="Bit")] System.Nullable<bool> closed, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipToID", DbType="Int")] System.Nullable<int> shipToID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DepositOverride", DbType="Bit")] System.Nullable<bool> depositOverride, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deposit", DbType="Money")] System.Nullable<decimal> deposit, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesRepID", DbType="Int")] System.Nullable<int> salesRepID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="Int")] System.Nullable<int> type, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(255)")] string comment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Taxable", DbType="Bit")] System.Nullable<bool> taxable, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImpBonificado", DbType="Money")] System.Nullable<decimal> impBonificado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, storeID, time, tax, total, lastUpdated, expirationOrDueDate, referenceNumber, customerFullName, customerAccountNumber, correoEnviado, subTotal, descuentos, isProforma, closed, customerID, shipToID, depositOverride, deposit, salesRepID, type, comment, taxable, impBonificado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCreaOrdenEntry")]
		public int spAVSCreaOrdenEntry(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cost", DbType="Money")] System.Nullable<decimal> cost, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemID", DbType="Int")] System.Nullable<int> itemID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemLookupCode", DbType="NVarChar(25)")] string itemLookupCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FullPrice", DbType="Money")] System.Nullable<decimal> fullPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PriceSource", DbType="Money")] System.Nullable<decimal> priceSource, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Money")] System.Nullable<decimal> price, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuantityOnOrder", DbType="Float")] System.Nullable<double> quantityOnOrder, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesRepID", DbType="Int")] System.Nullable<int> salesRepID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Taxable", DbType="Int")] System.Nullable<int> taxable, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DetailID", DbType="Int")] System.Nullable<int> detailID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(30)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuantityRTD", DbType="Float")] System.Nullable<double> quantityRTD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastUpdated", DbType="NVarChar(30)")] string lastUpdated, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(255)")] string comment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionTime", DbType="NVarChar(30)")] string transactionTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsBonificado", DbType="Bit")] System.Nullable<bool> isBonificado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cost, storeID, iD, orderID, itemID, itemLookupCode, fullPrice, priceSource, price, quantityOnOrder, salesRepID, taxable, detailID, description, quantityRTD, lastUpdated, comment, transactionTime, isBonificado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCrea_AR_LedgerEntry")]
		public int spAVSCrea_AR_LedgerEntry(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastUpdated", DbType="VarChar(19)")] string lastUpdated, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LinkType", DbType="Int")] System.Nullable<int> linkType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerAccountNumber", DbType="VarChar(30)")] string customerAccountNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentType", DbType="Int")] System.Nullable<int> documentType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostingDate", DbType="VarChar(19)")] string postingDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DueDate", DbType="VarChar(19)")] string dueDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LedgerType", DbType="Int")] System.Nullable<int> ledgerType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(50)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CurrencyID", DbType="Int")] System.Nullable<int> currencyID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CurrencyFactor", DbType="Float")] System.Nullable<double> currencyFactor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Positive", DbType="Bit")] System.Nullable<bool> positive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Open", DbType="Bit")] System.Nullable<bool> open, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClosingDate", DbType="VarChar(19)")] string closingDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonID", DbType="Int")] System.Nullable<int> reasonID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoldReasonID", DbType="Int")] System.Nullable<int> holdReasonID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UndoReasonID", DbType="Int")] System.Nullable<int> undoReasonID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="VarChar(255)")] string comment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayMethodID", DbType="Int")] System.Nullable<int> payMethodID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionID", DbType="Int")] System.Nullable<int> transactionID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppReference", DbType="VarChar(50)")] string appReference, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashierID", DbType="Int")] System.Nullable<int> cashierID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, lastUpdated, storeID, linkType, customerAccountNumber, documentType, postingDate, dueDate, ledgerType, description, currencyID, currencyFactor, positive, open, closingDate, reasonID, holdReasonID, undoReasonID, comment, payMethodID, transactionID, appReference, cashierID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCrea_Payment")]
		public int spAVSCrea_Payment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashierID", DbType="Int")] System.Nullable<int> cashierID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerAccountNumber", DbType="VarChar(50)")] string customerAccountNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Time", DbType="VarChar(19)")] string time, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Money")] System.Nullable<decimal> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="VarChar(255)")] string comment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppReference", DbType="VarChar(50)")] string appReference)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, cashierID, storeID, customerAccountNumber, time, amount, comment, appReference);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCrea_TenderEntry")]
		public int spAVSCrea_TenderEntry(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreditCardExpiration", DbType="VarChar(50)")] string creditCardExpiration, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderHistoryID", DbType="Int")] System.Nullable<int> orderHistoryID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DropPayoutID", DbType="Int")] System.Nullable<int> dropPayoutID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionNumber", DbType="Int")] System.Nullable<int> transactionNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenderCode", DbType="VarChar(5)")] string tenderCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentID", DbType="Int")] System.Nullable<int> paymentID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(30)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreditCardNumber", DbType="VarChar(25)")] string creditCardNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreditCardApprovalCode", DbType="VarChar(20)")] string creditCardApprovalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Money")] System.Nullable<decimal> amount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountHolder", DbType="VarChar(40)")] string accountHolder, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoundingError", DbType="Money")] System.Nullable<decimal> roundingError, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AmountForeign", DbType="Money")] System.Nullable<decimal> amountForeign, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankNumber", DbType="VarChar(25)")] string bankNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SerialNumber", DbType="VarChar(25)")] string serialNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(10)")] string state, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="License", DbType="VarChar(25)")] string license, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransitNumber", DbType="VarChar(25)")] string transitNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisaNetAuthorizationID", DbType="Int")] System.Nullable<int> visaNetAuthorizationID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DebitSurcharge", DbType="Money")] System.Nullable<decimal> debitSurcharge, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashBackSurcharge", DbType="Money")] System.Nullable<decimal> cashBackSurcharge, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsCreateNew", DbType="Bit")] System.Nullable<bool> isCreateNew, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppReference", DbType="VarChar(50)")] string appReference, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashierID", DbType="Int")] System.Nullable<int> cashierID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, creditCardExpiration, orderHistoryID, dropPayoutID, storeID, transactionNumber, tenderCode, paymentID, description, creditCardNumber, creditCardApprovalCode, amount, accountHolder, roundingError, amountForeign, bankNumber, serialNumber, state, license, transitNumber, visaNetAuthorizationID, debitSurcharge, cashBackSurcharge, isCreateNew, appReference, cashierID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCrea_AR_LedgerEntryDetail")]
		public int spAVSCrea_AR_LedgerEntryDetail(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LedgerEntryID", DbType="Int")] System.Nullable<int> ledgerEntryID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LedgerType", DbType="Int")] System.Nullable<int> ledgerType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DueDate", DbType="VarChar(19)")] string dueDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostingDate", DbType="VarChar(19)")] string postingDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DetailType", DbType="Int")] System.Nullable<int> detailType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Money")] System.Nullable<decimal> amount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AmountLCY", DbType="Money")] System.Nullable<decimal> amountLCY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AmountACY", DbType="Money")] System.Nullable<decimal> amountACY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppliedEntryID", DbType="Int")] System.Nullable<int> appliedEntryID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppliedAmount", DbType="Money")] System.Nullable<decimal> appliedAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UnapplyEntryID", DbType="Int")] System.Nullable<int> unapplyEntryID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UnapplyReasonID", DbType="Int")] System.Nullable<int> unapplyReasonID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppReference", DbType="VarChar(50)")] string appReference, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashierID", DbType="Int")] System.Nullable<int> cashierID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, ledgerEntryID, ledgerType, dueDate, postingDate, detailType, amount, amountLCY, amountACY, appliedEntryID, appliedAmount, unapplyEntryID, unapplyReasonID, appReference, cashierID, storeID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCrea_AR_Transaction")]
		public int spAVSCrea_AR_Transaction([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostingDate", DbType="VarChar(19)")] string postingDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerAccountNumber", DbType="VarChar(30)")] string customerAccountNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentType", DbType="Int")] System.Nullable<int> documentType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Money")] System.Nullable<decimal> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Balance", DbType="Money")] System.Nullable<decimal> balance, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CashierID", DbType="Int")] System.Nullable<int> cashierID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenderID", DbType="Int")] System.Nullable<int> tenderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceivableID", DbType="Int")] System.Nullable<int> receivableID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostedDate", DbType="VarChar(19)")] string postedDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppReference", DbType="VarChar(50)")] string appReference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, userID, postingDate, customerAccountNumber, orderID, documentType, amount, balance, cashierID, tenderID, receivableID, status, postedDate, appReference, storeID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVS_CreaPODOrder")]
		public int spAVS_CreaPODOrder(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RmsID", DbType="Int")] System.Nullable<int> rmsID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastUpdated", DbType="NVarChar(30)")] string lastUpdated, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="NVarChar(200)")] string number, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierID", DbType="Int")] System.Nullable<int> supplierID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateCreated", DbType="NVarChar(30)")] string dateCreated, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderDate", DbType="NVarChar(30)")] string orderDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequiredDate", DbType="NVarChar(30)")] string requiredDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DatePlaced", DbType="NVarChar(30)")] string datePlaced, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LocationType", DbType="Int")] System.Nullable<int> locationType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LocationID", DbType="Int")] System.Nullable<int> locationID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reference", DbType="NVarChar(30)")] string reference, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddrTo", DbType="NVarChar(255)")] string addrTo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipTo", DbType="NVarChar(255)")] string shipTo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PurchaserID", DbType="Int")] System.Nullable<int> purchaserID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipViaID", DbType="Int")] System.Nullable<int> shipViaID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayTermID", DbType="Int")] System.Nullable<int> payTermID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExchangeRate", DbType="Float")] System.Nullable<double> exchangeRate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(255)")] string comment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalAmmount", DbType="Money")] System.Nullable<decimal> totalAmmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalTax", DbType="Money")] System.Nullable<decimal> totalTax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierName", DbType="NVarChar(255)")] string supplierName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="NVarChar(50)")] string phoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="User", DbType="NVarChar(50)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, storeID, rmsID, lastUpdated, number, status, supplierID, dateCreated, orderDate, requiredDate, datePlaced, locationType, locationID, reference, addrTo, shipTo, purchaserID, shipViaID, payTermID, exchangeRate, comment, totalAmmount, totalTax, supplierName, phoneNumber, user);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCrea_PODOrderEntry")]
		public int spAVSCrea_PODOrderEntry(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastUpdated", DbType="NVarChar(50)")] string lastUpdated, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LineType", DbType="Int")] System.Nullable<int> lineType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LineNumber", DbType="Int")] System.Nullable<int> lineNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryType", DbType="Int")] System.Nullable<int> entryType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryID", DbType="Int")] System.Nullable<int> entryID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemTaxID", DbType="Int")] System.Nullable<int> itemTaxID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderNumber", DbType="NVarChar(25)")] string orderNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(50)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UOMID", DbType="Int")] System.Nullable<int> uOMID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantity", DbType="Float")] System.Nullable<double> quantity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="QtyReceived", DbType="Float")] System.Nullable<double> qtyReceived, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UnitCost", DbType="Money")] System.Nullable<decimal> unitCost, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(255)")] string comment)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, storeID, lastUpdated, orderID, lineType, lineNumber, entryType, entryID, itemTaxID, orderNumber, description, uOMID, quantity, qtyReceived, unitCost, comment);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class spAVSGetLocationsbyCriteriaResult
	{
		
		private string _RutaID;
		
		private System.Nullable<int> _CustomerID;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private System.Nullable<double> _Latitud;
		
		private System.Nullable<double> _Longitud;
		
		private System.Nullable<int> _Tipo;
		
		private System.Nullable<int> _CashierID;
		
		public spAVSGetLocationsbyCriteriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RutaID
		{
			get
			{
				return this._RutaID;
			}
			set
			{
				if ((this._RutaID != value))
				{
					this._RutaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int")]
		public System.Nullable<int> CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NChar(255)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitud", DbType="Float")]
		public System.Nullable<double> Latitud
		{
			get
			{
				return this._Latitud;
			}
			set
			{
				if ((this._Latitud != value))
				{
					this._Latitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitud", DbType="Float")]
		public System.Nullable<double> Longitud
		{
			get
			{
				return this._Longitud;
			}
			set
			{
				if ((this._Longitud != value))
				{
					this._Longitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="Int")]
		public System.Nullable<int> Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashierID", DbType="Int")]
		public System.Nullable<int> CashierID
		{
			get
			{
				return this._CashierID;
			}
			set
			{
				if ((this._CashierID != value))
				{
					this._CashierID = value;
				}
			}
		}
	}
	
	public partial class spAVSGetRoutesbyCriteriaResult
	{
		
		private int _AutoID;
		
		private int _StoreID;
		
		private string _ReferenceNumber;
		
		private string _Nombre;
		
		private int _CashierID;
		
		public spAVSGetRoutesbyCriteriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoID", DbType="Int NOT NULL")]
		public int AutoID
		{
			get
			{
				return this._AutoID;
			}
			set
			{
				if ((this._AutoID != value))
				{
					this._AutoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", DbType="Int NOT NULL")]
		public int StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this._StoreID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReferenceNumber
		{
			get
			{
				return this._ReferenceNumber;
			}
			set
			{
				if ((this._ReferenceNumber != value))
				{
					this._ReferenceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashierID", DbType="Int NOT NULL")]
		public int CashierID
		{
			get
			{
				return this._CashierID;
			}
			set
			{
				if ((this._CashierID != value))
				{
					this._CashierID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
