#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RMHC_DEMO")]
	public partial class LINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LINQDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BM_POS_MSVConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCreaOrden")]
		public int spAVSCreaOrden([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdOrdenOnline", DbType="VarChar(30)")] string idOrdenOnline, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IpAddress", DbType="VarChar(30)")] string ipAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountNumber", DbType="VarChar(13)")] string accountNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tax", DbType="Money")] System.Nullable<decimal> tax, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Money")] System.Nullable<decimal> total, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceNumber", DbType="NVarChar(50)")] string referenceNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TypeTransac", DbType="Int")] System.Nullable<int> typeTransac)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrdenOnline, ipAddress, accountNumber, tax, total, referenceNumber, typeTransac);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVSCreaOrdenEntry")]
		public int spAVSCreaOrdenEntry([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceNumber", DbType="NVarChar(50)")] string referenceNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sku", DbType="VarChar(30)")] string sku, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Decimal(18,2)")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuantityOnOrder", DbType="Decimal(18,2)")] System.Nullable<decimal> quantityOnOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemDescription", DbType="NVarChar(30)")] string itemDescription)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), referenceNumber, sku, price, quantityOnOrder, itemDescription);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
