#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAPI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GALERIA_MX")]
	public partial class RMHCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public RMHCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RMHCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RMHCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RMHCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spWS_AR_Detail")]
		public ISingleResult<spWS_AR_DetailResult> spWS_AR_Detail()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spWS_AR_DetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spWS_InsertActualizaCustomers")]
		public ISingleResult<spWS_InsertActualizaCustomersResult> spWS_InsertActualizaCustomers(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountNumber", DbType="VarChar(20)")] string accountNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="VarChar(30)")] string firstName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="VarChar(50)")] string lastName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="VarChar(10)")] string phoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FaxNumber", DbType="VarChar(10)")] string faxNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddress", DbType="VarChar(255)")] string emailAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomText1", DbType="VarChar(20)")] string customText1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomText2", DbType="VarChar(20)")] string customText2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomText3", DbType="VarChar(20)")] string customText3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomText4", DbType="VarChar(20)")] string customText4, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(50)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomText5", DbType="VarChar(20)")] string customText5, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Source", DbType="VarChar(50)")] string source, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string tipo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodVendedor", DbType="VarChar(10)")] string codVendedor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiasCredito", DbType="Int")] System.Nullable<int> diasCredito)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountNumber, firstName, lastName, phoneNumber, faxNumber, emailAddress, customText1, customText2, customText3, customText4, address, customText5, source, tipo, codVendedor, diasCredito);
			return ((ISingleResult<spWS_InsertActualizaCustomersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spWS_GetProductsbyCriteria")]
		public ISingleResult<spWS_GetProductsbyCriteriaResult> spWS_GetProductsbyCriteria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criteria", DbType="NVarChar(40)")] string criteria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteria);
			return ((ISingleResult<spWS_GetProductsbyCriteriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spWS_GetProducts")]
		public ISingleResult<spWS_GetProductsResult> spWS_GetProducts([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STOREID", DbType="Int")] System.Nullable<int> sTOREID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="Int")] System.Nullable<int> tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTOREID, tipo);
			return ((ISingleResult<spWS_GetProductsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAVS_GETPAYMENTS_RMH")]
		public ISingleResult<spAVS_GETPAYMENTS_RMHResult> spAVS_GETPAYMENTS_RMH([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STORE_ID", DbType="Int")] System.Nullable<int> sTORE_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SALESREP_ID", DbType="Int")] System.Nullable<int> sALESREP_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTORE_ID, sALESREP_ID);
			return ((ISingleResult<spAVS_GETPAYMENTS_RMHResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spWS_GetPOD_Detail")]
		public ISingleResult<spWS_GetPOD_DetailResult> spWS_GetPOD_Detail()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spWS_GetPOD_DetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spWS_GetPOD_Header")]
		public ISingleResult<spWS_GetPOD_HeaderResult> spWS_GetPOD_Header()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spWS_GetPOD_HeaderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spWS_GetSalesRep")]
		public ISingleResult<spWS_GetSalesRepResult> spWS_GetSalesRep()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spWS_GetSalesRepResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spWS_GetCustomers")]
		public ISingleResult<spWS_GetCustomersResult> spWS_GetCustomers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spWS_GetCustomersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spWS_GetCustomersByStoreID")]
		public ISingleResult<spWS_GetCustomersByStoreIDResult> spWS_GetCustomersByStoreID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoreID", DbType="Int")] System.Nullable<int> storeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), storeID);
			return ((ISingleResult<spWS_GetCustomersByStoreIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spWS_GetCustomersbyCriteria")]
		public ISingleResult<spWS_GetCustomersbyCriteriaResult> spWS_GetCustomersbyCriteria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criteria", DbType="VarChar(40)")] string criteria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteria);
			return ((ISingleResult<spWS_GetCustomersbyCriteriaResult>)(result.ReturnValue));
		}
	}
	
	public partial class spWS_AR_DetailResult
	{
		
		private string _Number;
		
		private string _Name;
		
		private string _Email;
		
		private System.DateTime _DueDate;
		
		private System.DateTime _PostingDate;
		
		private string _Reference;
		
		private int _TransactionID;
		
		private decimal _Amount;
		
		private System.Nullable<int> _DueDays;
		
		public spWS_AR_DetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="DateTime NOT NULL")]
		public System.DateTime DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this._DueDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostingDate", DbType="DateTime NOT NULL")]
		public System.DateTime PostingDate
		{
			get
			{
				return this._PostingDate;
			}
			set
			{
				if ((this._PostingDate != value))
				{
					this._PostingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference", DbType="NVarChar(4000)")]
		public string Reference
		{
			get
			{
				return this._Reference;
			}
			set
			{
				if ((this._Reference != value))
				{
					this._Reference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="Int NOT NULL")]
		public int TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this._TransactionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDays", DbType="Int")]
		public System.Nullable<int> DueDays
		{
			get
			{
				return this._DueDays;
			}
			set
			{
				if ((this._DueDays != value))
				{
					this._DueDays = value;
				}
			}
		}
	}
	
	public partial class spWS_InsertActualizaCustomersResult
	{
		
		private string _RESPUESTA;
		
		public spWS_InsertActualizaCustomersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESPUESTA", DbType="VarChar(30)")]
		public string RESPUESTA
		{
			get
			{
				return this._RESPUESTA;
			}
			set
			{
				if ((this._RESPUESTA != value))
				{
					this._RESPUESTA = value;
				}
			}
		}
	}
	
	public partial class spWS_GetProductsbyCriteriaResult
	{
		
		private int _ID;
		
		private string _ItemLookupCode;
		
		private string _Description;
		
		private double _Quantity;
		
		private double _QuantityCommitted;
		
		private int _DepartmentID;
		
		private int _CategoryID;
		
		private decimal _Price;
		
		private decimal _PriceA;
		
		private decimal _PriceB;
		
		private decimal _PriceC;
		
		private int _TaxID;
		
		private decimal _Cost;
		
		private string _ExtendedDescription;
		
		private string _SubDescription1;
		
		private string _SubDescription2;
		
		private string _SubDescription3;
		
		private bool _WebItem;
		
		public spWS_GetProductsbyCriteriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemLookupCode", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string ItemLookupCode
		{
			get
			{
				return this._ItemLookupCode;
			}
			set
			{
				if ((this._ItemLookupCode != value))
				{
					this._ItemLookupCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float NOT NULL")]
		public double Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantityCommitted", DbType="Float NOT NULL")]
		public double QuantityCommitted
		{
			get
			{
				return this._QuantityCommitted;
			}
			set
			{
				if ((this._QuantityCommitted != value))
				{
					this._QuantityCommitted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="Int NOT NULL")]
		public int DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this._DepartmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int NOT NULL")]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this._CategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceA", DbType="Money NOT NULL")]
		public decimal PriceA
		{
			get
			{
				return this._PriceA;
			}
			set
			{
				if ((this._PriceA != value))
				{
					this._PriceA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceB", DbType="Money NOT NULL")]
		public decimal PriceB
		{
			get
			{
				return this._PriceB;
			}
			set
			{
				if ((this._PriceB != value))
				{
					this._PriceB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceC", DbType="Money NOT NULL")]
		public decimal PriceC
		{
			get
			{
				return this._PriceC;
			}
			set
			{
				if ((this._PriceC != value))
				{
					this._PriceC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxID", DbType="Int NOT NULL")]
		public int TaxID
		{
			get
			{
				return this._TaxID;
			}
			set
			{
				if ((this._TaxID != value))
				{
					this._TaxID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Money NOT NULL")]
		public decimal Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this._Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtendedDescription", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ExtendedDescription
		{
			get
			{
				return this._ExtendedDescription;
			}
			set
			{
				if ((this._ExtendedDescription != value))
				{
					this._ExtendedDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubDescription1", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SubDescription1
		{
			get
			{
				return this._SubDescription1;
			}
			set
			{
				if ((this._SubDescription1 != value))
				{
					this._SubDescription1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubDescription2", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SubDescription2
		{
			get
			{
				return this._SubDescription2;
			}
			set
			{
				if ((this._SubDescription2 != value))
				{
					this._SubDescription2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubDescription3", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SubDescription3
		{
			get
			{
				return this._SubDescription3;
			}
			set
			{
				if ((this._SubDescription3 != value))
				{
					this._SubDescription3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebItem", DbType="Bit NOT NULL")]
		public bool WebItem
		{
			get
			{
				return this._WebItem;
			}
			set
			{
				if ((this._WebItem != value))
				{
					this._WebItem = value;
				}
			}
		}
	}
	
	public partial class spWS_GetProductsResult
	{
		
		private int _ID;
		
		private string _ItemLookupCode;
		
		private string _ExtendedDescription;
		
		private System.Nullable<double> _Quantity;
		
		private double _QuantityCommitted;
		
		private int _DepartmentID;
		
		private int _CategoryID;
		
		private decimal _PRICE;
		
		private decimal _PriceA;
		
		private decimal _PriceB;
		
		private decimal _PriceC;
		
		private int _TaxID;
		
		private decimal _Cost;
		
		private string _Description;
		
		private string _SubDescription1;
		
		private string _SubDescription2;
		
		private string _SubDescription3;
		
		private bool _WebItem;
		
		private float _Percentage;
		
		private string _TaxDescription;
		
		private string _PROMO;
		
		private double _PROMO_QTY;
		
		private double _PROMO_REGALIA;
		
		private double _PROMO_VALOR_REGALIA;
		
		public spWS_GetProductsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemLookupCode", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string ItemLookupCode
		{
			get
			{
				return this._ItemLookupCode;
			}
			set
			{
				if ((this._ItemLookupCode != value))
				{
					this._ItemLookupCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtendedDescription", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string ExtendedDescription
		{
			get
			{
				return this._ExtendedDescription;
			}
			set
			{
				if ((this._ExtendedDescription != value))
				{
					this._ExtendedDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float")]
		public System.Nullable<double> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantityCommitted", DbType="Float NOT NULL")]
		public double QuantityCommitted
		{
			get
			{
				return this._QuantityCommitted;
			}
			set
			{
				if ((this._QuantityCommitted != value))
				{
					this._QuantityCommitted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="Int NOT NULL")]
		public int DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this._DepartmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int NOT NULL")]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this._CategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Money NOT NULL")]
		public decimal PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this._PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceA", DbType="Money NOT NULL")]
		public decimal PriceA
		{
			get
			{
				return this._PriceA;
			}
			set
			{
				if ((this._PriceA != value))
				{
					this._PriceA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceB", DbType="Money NOT NULL")]
		public decimal PriceB
		{
			get
			{
				return this._PriceB;
			}
			set
			{
				if ((this._PriceB != value))
				{
					this._PriceB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceC", DbType="Money NOT NULL")]
		public decimal PriceC
		{
			get
			{
				return this._PriceC;
			}
			set
			{
				if ((this._PriceC != value))
				{
					this._PriceC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxID", DbType="Int NOT NULL")]
		public int TaxID
		{
			get
			{
				return this._TaxID;
			}
			set
			{
				if ((this._TaxID != value))
				{
					this._TaxID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Money NOT NULL")]
		public decimal Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this._Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubDescription1", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SubDescription1
		{
			get
			{
				return this._SubDescription1;
			}
			set
			{
				if ((this._SubDescription1 != value))
				{
					this._SubDescription1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubDescription2", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SubDescription2
		{
			get
			{
				return this._SubDescription2;
			}
			set
			{
				if ((this._SubDescription2 != value))
				{
					this._SubDescription2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubDescription3", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SubDescription3
		{
			get
			{
				return this._SubDescription3;
			}
			set
			{
				if ((this._SubDescription3 != value))
				{
					this._SubDescription3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebItem", DbType="Bit NOT NULL")]
		public bool WebItem
		{
			get
			{
				return this._WebItem;
			}
			set
			{
				if ((this._WebItem != value))
				{
					this._WebItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Percentage", DbType="Real NOT NULL")]
		public float Percentage
		{
			get
			{
				return this._Percentage;
			}
			set
			{
				if ((this._Percentage != value))
				{
					this._Percentage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxDescription", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string TaxDescription
		{
			get
			{
				return this._TaxDescription;
			}
			set
			{
				if ((this._TaxDescription != value))
				{
					this._TaxDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROMO", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PROMO
		{
			get
			{
				return this._PROMO;
			}
			set
			{
				if ((this._PROMO != value))
				{
					this._PROMO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROMO_QTY", DbType="Float NOT NULL")]
		public double PROMO_QTY
		{
			get
			{
				return this._PROMO_QTY;
			}
			set
			{
				if ((this._PROMO_QTY != value))
				{
					this._PROMO_QTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROMO_REGALIA", DbType="Float NOT NULL")]
		public double PROMO_REGALIA
		{
			get
			{
				return this._PROMO_REGALIA;
			}
			set
			{
				if ((this._PROMO_REGALIA != value))
				{
					this._PROMO_REGALIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROMO_VALOR_REGALIA", DbType="Float NOT NULL")]
		public double PROMO_VALOR_REGALIA
		{
			get
			{
				return this._PROMO_VALOR_REGALIA;
			}
			set
			{
				if ((this._PROMO_VALOR_REGALIA != value))
				{
					this._PROMO_VALOR_REGALIA = value;
				}
			}
		}
	}
	
	public partial class spAVS_GETPAYMENTS_RMHResult
	{
		
		private string _CLAVE50;
		
		private string _CLAVE20;
		
		private int _TRANSACTIONNUMBER;
		
		private int _STORE_ID;
		
		private string _COD_CLIENTE;
		
		private string _CEDULA_CLIENTE;
		
		private string _NOMBRE_CLIENTE;
		
		private string _FECHA_TRANSAC;
		
		private string _FECHA_VENCE;
		
		private System.Nullable<decimal> _MONTO;
		
		private System.Nullable<decimal> _MONTO_ABONADO;
		
		public spAVS_GETPAYMENTS_RMHResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVE50", DbType="VarChar(50)")]
		public string CLAVE50
		{
			get
			{
				return this._CLAVE50;
			}
			set
			{
				if ((this._CLAVE50 != value))
				{
					this._CLAVE50 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVE20", DbType="VarChar(20)")]
		public string CLAVE20
		{
			get
			{
				return this._CLAVE20;
			}
			set
			{
				if ((this._CLAVE20 != value))
				{
					this._CLAVE20 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSACTIONNUMBER", DbType="Int NOT NULL")]
		public int TRANSACTIONNUMBER
		{
			get
			{
				return this._TRANSACTIONNUMBER;
			}
			set
			{
				if ((this._TRANSACTIONNUMBER != value))
				{
					this._TRANSACTIONNUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STORE_ID", DbType="Int NOT NULL")]
		public int STORE_ID
		{
			get
			{
				return this._STORE_ID;
			}
			set
			{
				if ((this._STORE_ID != value))
				{
					this._STORE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_CLIENTE", DbType="NVarChar(20)")]
		public string COD_CLIENTE
		{
			get
			{
				return this._COD_CLIENTE;
			}
			set
			{
				if ((this._COD_CLIENTE != value))
				{
					this._COD_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(15)")]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					this._CEDULA_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CLIENTE", DbType="NVarChar(50)")]
		public string NOMBRE_CLIENTE
		{
			get
			{
				return this._NOMBRE_CLIENTE;
			}
			set
			{
				if ((this._NOMBRE_CLIENTE != value))
				{
					this._NOMBRE_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TRANSAC", DbType="NVarChar(4000)")]
		public string FECHA_TRANSAC
		{
			get
			{
				return this._FECHA_TRANSAC;
			}
			set
			{
				if ((this._FECHA_TRANSAC != value))
				{
					this._FECHA_TRANSAC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_VENCE", DbType="NVarChar(4000)")]
		public string FECHA_VENCE
		{
			get
			{
				return this._FECHA_VENCE;
			}
			set
			{
				if ((this._FECHA_VENCE != value))
				{
					this._FECHA_VENCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO", DbType="Money")]
		public System.Nullable<decimal> MONTO
		{
			get
			{
				return this._MONTO;
			}
			set
			{
				if ((this._MONTO != value))
				{
					this._MONTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO_ABONADO", DbType="Money")]
		public System.Nullable<decimal> MONTO_ABONADO
		{
			get
			{
				return this._MONTO_ABONADO;
			}
			set
			{
				if ((this._MONTO_ABONADO != value))
				{
					this._MONTO_ABONADO = value;
				}
			}
		}
	}
	
	public partial class spWS_GetPOD_DetailResult
	{
		
		private int _ID;
		
		private string _Number;
		
		private int _ID1;
		
		private System.Data.Linq.Binary _DBTimeStamp;
		
		private int _StoreID;
		
		private int _LinkID;
		
		private int _RmsID;
		
		private System.DateTime _LastUpdated;
		
		private int _OrderID;
		
		private int _LineType;
		
		private int _LineNumber;
		
		private int _EntryType;
		
		private int _EntryID;
		
		private int _ItemTaxID;
		
		private string _OrderNumber;
		
		private string _Description;
		
		private int _UOMID;
		
		private double _Quantity;
		
		private double _QtyReceived;
		
		private double _QtyToReceive;
		
		private double _QtyInvoiced;
		
		private double _QtyToInvoice;
		
		private double _QtyPerUOM;
		
		private decimal _UnitCost;
		
		private double _LineDiscRate;
		
		private double _TaxRate;
		
		private int _LinkedEntryID;
		
		private System.Nullable<int> _ParentEntryID;
		
		private int _InventoryOfflineID;
		
		private string _Comment;
		
		private bool _BIDPrice;
		
		private System.Guid _SyncGuid;
		
		public spWS_GetPOD_DetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="NVarChar(200)")]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID1", DbType="Int NOT NULL")]
		public int ID1
		{
			get
			{
				return this._ID1;
			}
			set
			{
				if ((this._ID1 != value))
				{
					this._ID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBTimeStamp", DbType="rowversion")]
		public System.Data.Linq.Binary DBTimeStamp
		{
			get
			{
				return this._DBTimeStamp;
			}
			set
			{
				if ((this._DBTimeStamp != value))
				{
					this._DBTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", DbType="Int NOT NULL")]
		public int StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this._StoreID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkID", DbType="Int NOT NULL")]
		public int LinkID
		{
			get
			{
				return this._LinkID;
			}
			set
			{
				if ((this._LinkID != value))
				{
					this._LinkID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RmsID", DbType="Int NOT NULL")]
		public int RmsID
		{
			get
			{
				return this._RmsID;
			}
			set
			{
				if ((this._RmsID != value))
				{
					this._RmsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpdated
		{
			get
			{
				return this._LastUpdated;
			}
			set
			{
				if ((this._LastUpdated != value))
				{
					this._LastUpdated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Int NOT NULL")]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this._OrderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineType", DbType="Int NOT NULL")]
		public int LineType
		{
			get
			{
				return this._LineType;
			}
			set
			{
				if ((this._LineType != value))
				{
					this._LineType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineNumber", DbType="Int NOT NULL")]
		public int LineNumber
		{
			get
			{
				return this._LineNumber;
			}
			set
			{
				if ((this._LineNumber != value))
				{
					this._LineNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryType", DbType="Int NOT NULL")]
		public int EntryType
		{
			get
			{
				return this._EntryType;
			}
			set
			{
				if ((this._EntryType != value))
				{
					this._EntryType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryID", DbType="Int NOT NULL")]
		public int EntryID
		{
			get
			{
				return this._EntryID;
			}
			set
			{
				if ((this._EntryID != value))
				{
					this._EntryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemTaxID", DbType="Int NOT NULL")]
		public int ItemTaxID
		{
			get
			{
				return this._ItemTaxID;
			}
			set
			{
				if ((this._ItemTaxID != value))
				{
					this._ItemTaxID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this._OrderNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UOMID", DbType="Int NOT NULL")]
		public int UOMID
		{
			get
			{
				return this._UOMID;
			}
			set
			{
				if ((this._UOMID != value))
				{
					this._UOMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float NOT NULL")]
		public double Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyReceived", DbType="Float NOT NULL")]
		public double QtyReceived
		{
			get
			{
				return this._QtyReceived;
			}
			set
			{
				if ((this._QtyReceived != value))
				{
					this._QtyReceived = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyToReceive", DbType="Float NOT NULL")]
		public double QtyToReceive
		{
			get
			{
				return this._QtyToReceive;
			}
			set
			{
				if ((this._QtyToReceive != value))
				{
					this._QtyToReceive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyInvoiced", DbType="Float NOT NULL")]
		public double QtyInvoiced
		{
			get
			{
				return this._QtyInvoiced;
			}
			set
			{
				if ((this._QtyInvoiced != value))
				{
					this._QtyInvoiced = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyToInvoice", DbType="Float NOT NULL")]
		public double QtyToInvoice
		{
			get
			{
				return this._QtyToInvoice;
			}
			set
			{
				if ((this._QtyToInvoice != value))
				{
					this._QtyToInvoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyPerUOM", DbType="Float NOT NULL")]
		public double QtyPerUOM
		{
			get
			{
				return this._QtyPerUOM;
			}
			set
			{
				if ((this._QtyPerUOM != value))
				{
					this._QtyPerUOM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitCost", DbType="Money NOT NULL")]
		public decimal UnitCost
		{
			get
			{
				return this._UnitCost;
			}
			set
			{
				if ((this._UnitCost != value))
				{
					this._UnitCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineDiscRate", DbType="Float NOT NULL")]
		public double LineDiscRate
		{
			get
			{
				return this._LineDiscRate;
			}
			set
			{
				if ((this._LineDiscRate != value))
				{
					this._LineDiscRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRate", DbType="Float NOT NULL")]
		public double TaxRate
		{
			get
			{
				return this._TaxRate;
			}
			set
			{
				if ((this._TaxRate != value))
				{
					this._TaxRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkedEntryID", DbType="Int NOT NULL")]
		public int LinkedEntryID
		{
			get
			{
				return this._LinkedEntryID;
			}
			set
			{
				if ((this._LinkedEntryID != value))
				{
					this._LinkedEntryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentEntryID", DbType="Int")]
		public System.Nullable<int> ParentEntryID
		{
			get
			{
				return this._ParentEntryID;
			}
			set
			{
				if ((this._ParentEntryID != value))
				{
					this._ParentEntryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventoryOfflineID", DbType="Int NOT NULL")]
		public int InventoryOfflineID
		{
			get
			{
				return this._InventoryOfflineID;
			}
			set
			{
				if ((this._InventoryOfflineID != value))
				{
					this._InventoryOfflineID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIDPrice", DbType="Bit NOT NULL")]
		public bool BIDPrice
		{
			get
			{
				return this._BIDPrice;
			}
			set
			{
				if ((this._BIDPrice != value))
				{
					this._BIDPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyncGuid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SyncGuid
		{
			get
			{
				return this._SyncGuid;
			}
			set
			{
				if ((this._SyncGuid != value))
				{
					this._SyncGuid = value;
				}
			}
		}
	}
	
	public partial class spWS_GetPOD_HeaderResult
	{
		
		private int _ID;
		
		private System.Data.Linq.Binary _DBTimeStamp;
		
		private int _StoreID;
		
		private int _LinkID;
		
		private int _RmsID;
		
		private System.DateTime _LastUpdated;
		
		private int _DocType;
		
		private int _DocSource;
		
		private int _DocOption;
		
		private string _Number;
		
		private int _Status;
		
		private int _DelStatus;
		
		private int _InvStatus;
		
		private int _AllocationID;
		
		private int _SupplierID;
		
		private int _SupplierTaxID;
		
		private System.DateTime _DateCreated;
		
		private System.DateTime _OrderDate;
		
		private System.DateTime _RequiredDate;
		
		private System.Nullable<System.DateTime> _DatePlaced;
		
		private int _LocationType;
		
		private int _LocationID;
		
		private string _Reference;
		
		private string _AddrTo;
		
		private string _ShipTo;
		
		private int _PurchaserID;
		
		private string _Requisitioner;
		
		private int _ShipViaID;
		
		private string _FOBPoint;
		
		private string _Freight;
		
		private int _PayTermID;
		
		private int _CurrencyID;
		
		private double _ExchangeRate;
		
		private int _InvDiscMode;
		
		private double _InvDiscValue;
		
		private string _Comment;
		
		private string _ExternalDocNo;
		
		private string _SupplierDocNo;
		
		private string _SupplierDelNo;
		
		private System.Nullable<System.DateTime> _SupplierDelDate;
		
		private string _SupplierInvNo;
		
		private System.Nullable<System.DateTime> _SupplierInvDate;
		
		private decimal _SupplierInvAmt;
		
		private string _PostingComment;
		
		private decimal _TotalAmount;
		
		private decimal _TotalTax;
		
		private int _PoType;
		
		private System.Guid _SyncGuid;
		
		private string _SupplierName;
		
		private string _PhoneNumber;
		
		public spWS_GetPOD_HeaderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBTimeStamp", DbType="rowversion")]
		public System.Data.Linq.Binary DBTimeStamp
		{
			get
			{
				return this._DBTimeStamp;
			}
			set
			{
				if ((this._DBTimeStamp != value))
				{
					this._DBTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", DbType="Int NOT NULL")]
		public int StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this._StoreID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkID", DbType="Int NOT NULL")]
		public int LinkID
		{
			get
			{
				return this._LinkID;
			}
			set
			{
				if ((this._LinkID != value))
				{
					this._LinkID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RmsID", DbType="Int NOT NULL")]
		public int RmsID
		{
			get
			{
				return this._RmsID;
			}
			set
			{
				if ((this._RmsID != value))
				{
					this._RmsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpdated
		{
			get
			{
				return this._LastUpdated;
			}
			set
			{
				if ((this._LastUpdated != value))
				{
					this._LastUpdated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocType", DbType="Int NOT NULL")]
		public int DocType
		{
			get
			{
				return this._DocType;
			}
			set
			{
				if ((this._DocType != value))
				{
					this._DocType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocSource", DbType="Int NOT NULL")]
		public int DocSource
		{
			get
			{
				return this._DocSource;
			}
			set
			{
				if ((this._DocSource != value))
				{
					this._DocSource = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocOption", DbType="Int NOT NULL")]
		public int DocOption
		{
			get
			{
				return this._DocOption;
			}
			set
			{
				if ((this._DocOption != value))
				{
					this._DocOption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="NVarChar(200)")]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DelStatus", DbType="Int NOT NULL")]
		public int DelStatus
		{
			get
			{
				return this._DelStatus;
			}
			set
			{
				if ((this._DelStatus != value))
				{
					this._DelStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvStatus", DbType="Int NOT NULL")]
		public int InvStatus
		{
			get
			{
				return this._InvStatus;
			}
			set
			{
				if ((this._InvStatus != value))
				{
					this._InvStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllocationID", DbType="Int NOT NULL")]
		public int AllocationID
		{
			get
			{
				return this._AllocationID;
			}
			set
			{
				if ((this._AllocationID != value))
				{
					this._AllocationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierID", DbType="Int NOT NULL")]
		public int SupplierID
		{
			get
			{
				return this._SupplierID;
			}
			set
			{
				if ((this._SupplierID != value))
				{
					this._SupplierID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierTaxID", DbType="Int NOT NULL")]
		public int SupplierTaxID
		{
			get
			{
				return this._SupplierTaxID;
			}
			set
			{
				if ((this._SupplierTaxID != value))
				{
					this._SupplierTaxID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDate", DbType="DateTime NOT NULL")]
		public System.DateTime OrderDate
		{
			get
			{
				return this._OrderDate;
			}
			set
			{
				if ((this._OrderDate != value))
				{
					this._OrderDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequiredDate", DbType="DateTime NOT NULL")]
		public System.DateTime RequiredDate
		{
			get
			{
				return this._RequiredDate;
			}
			set
			{
				if ((this._RequiredDate != value))
				{
					this._RequiredDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePlaced", DbType="DateTime")]
		public System.Nullable<System.DateTime> DatePlaced
		{
			get
			{
				return this._DatePlaced;
			}
			set
			{
				if ((this._DatePlaced != value))
				{
					this._DatePlaced = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationType", DbType="Int NOT NULL")]
		public int LocationType
		{
			get
			{
				return this._LocationType;
			}
			set
			{
				if ((this._LocationType != value))
				{
					this._LocationType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL")]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this._LocationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Reference
		{
			get
			{
				return this._Reference;
			}
			set
			{
				if ((this._Reference != value))
				{
					this._Reference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddrTo", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string AddrTo
		{
			get
			{
				return this._AddrTo;
			}
			set
			{
				if ((this._AddrTo != value))
				{
					this._AddrTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipTo", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ShipTo
		{
			get
			{
				return this._ShipTo;
			}
			set
			{
				if ((this._ShipTo != value))
				{
					this._ShipTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaserID", DbType="Int NOT NULL")]
		public int PurchaserID
		{
			get
			{
				return this._PurchaserID;
			}
			set
			{
				if ((this._PurchaserID != value))
				{
					this._PurchaserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requisitioner", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Requisitioner
		{
			get
			{
				return this._Requisitioner;
			}
			set
			{
				if ((this._Requisitioner != value))
				{
					this._Requisitioner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipViaID", DbType="Int NOT NULL")]
		public int ShipViaID
		{
			get
			{
				return this._ShipViaID;
			}
			set
			{
				if ((this._ShipViaID != value))
				{
					this._ShipViaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOBPoint", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string FOBPoint
		{
			get
			{
				return this._FOBPoint;
			}
			set
			{
				if ((this._FOBPoint != value))
				{
					this._FOBPoint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Freight", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Freight
		{
			get
			{
				return this._Freight;
			}
			set
			{
				if ((this._Freight != value))
				{
					this._Freight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayTermID", DbType="Int NOT NULL")]
		public int PayTermID
		{
			get
			{
				return this._PayTermID;
			}
			set
			{
				if ((this._PayTermID != value))
				{
					this._PayTermID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyID", DbType="Int NOT NULL")]
		public int CurrencyID
		{
			get
			{
				return this._CurrencyID;
			}
			set
			{
				if ((this._CurrencyID != value))
				{
					this._CurrencyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeRate", DbType="Float NOT NULL")]
		public double ExchangeRate
		{
			get
			{
				return this._ExchangeRate;
			}
			set
			{
				if ((this._ExchangeRate != value))
				{
					this._ExchangeRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvDiscMode", DbType="Int NOT NULL")]
		public int InvDiscMode
		{
			get
			{
				return this._InvDiscMode;
			}
			set
			{
				if ((this._InvDiscMode != value))
				{
					this._InvDiscMode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvDiscValue", DbType="Float NOT NULL")]
		public double InvDiscValue
		{
			get
			{
				return this._InvDiscValue;
			}
			set
			{
				if ((this._InvDiscValue != value))
				{
					this._InvDiscValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExternalDocNo", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ExternalDocNo
		{
			get
			{
				return this._ExternalDocNo;
			}
			set
			{
				if ((this._ExternalDocNo != value))
				{
					this._ExternalDocNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierDocNo", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SupplierDocNo
		{
			get
			{
				return this._SupplierDocNo;
			}
			set
			{
				if ((this._SupplierDocNo != value))
				{
					this._SupplierDocNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierDelNo", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SupplierDelNo
		{
			get
			{
				return this._SupplierDelNo;
			}
			set
			{
				if ((this._SupplierDelNo != value))
				{
					this._SupplierDelNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierDelDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SupplierDelDate
		{
			get
			{
				return this._SupplierDelDate;
			}
			set
			{
				if ((this._SupplierDelDate != value))
				{
					this._SupplierDelDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierInvNo", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SupplierInvNo
		{
			get
			{
				return this._SupplierInvNo;
			}
			set
			{
				if ((this._SupplierInvNo != value))
				{
					this._SupplierInvNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierInvDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SupplierInvDate
		{
			get
			{
				return this._SupplierInvDate;
			}
			set
			{
				if ((this._SupplierInvDate != value))
				{
					this._SupplierInvDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierInvAmt", DbType="Money NOT NULL")]
		public decimal SupplierInvAmt
		{
			get
			{
				return this._SupplierInvAmt;
			}
			set
			{
				if ((this._SupplierInvAmt != value))
				{
					this._SupplierInvAmt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostingComment", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PostingComment
		{
			get
			{
				return this._PostingComment;
			}
			set
			{
				if ((this._PostingComment != value))
				{
					this._PostingComment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Money NOT NULL")]
		public decimal TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this._TotalAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalTax", DbType="Money NOT NULL")]
		public decimal TotalTax
		{
			get
			{
				return this._TotalTax;
			}
			set
			{
				if ((this._TotalTax != value))
				{
					this._TotalTax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoType", DbType="Int NOT NULL")]
		public int PoType
		{
			get
			{
				return this._PoType;
			}
			set
			{
				if ((this._PoType != value))
				{
					this._PoType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyncGuid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SyncGuid
		{
			get
			{
				return this._SyncGuid;
			}
			set
			{
				if ((this._SyncGuid != value))
				{
					this._SyncGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
	}
	
	public partial class spWS_GetSalesRepResult
	{
		
		private int _ID;
		
		private string _Number;
		
		private string _Nombre;
		
		public spWS_GetSalesRepResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class spWS_GetCustomersResult
	{
		
		private int _ID;
		
		private string _AccountNumber;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _PhoneNumber1;
		
		private string _PhoneNumber2;
		
		private string _EmailAddress;
		
		private string _STATE;
		
		private string _CITY;
		
		private string _CITY2;
		
		private string _ZIP;
		
		private string _Address;
		
		private System.Nullable<int> _CreditDays;
		
		private string _SOURCE;
		
		private System.Nullable<decimal> _ClosingBalance;
		
		private System.Nullable<decimal> _CreditLimit;
		
		private System.Nullable<decimal> _Available;
		
		private short _PriceLevel;
		
		private string _Notes;
		
		private decimal _TotalSales;
		
		private decimal _TotalSavings;
		
		private int _TotalVisits;
		
		public spWS_GetCustomersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this._AccountNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber1", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhoneNumber1
		{
			get
			{
				return this._PhoneNumber1;
			}
			set
			{
				if ((this._PhoneNumber1 != value))
				{
					this._PhoneNumber1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber2", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhoneNumber2
		{
			get
			{
				return this._PhoneNumber2;
			}
			set
			{
				if ((this._PhoneNumber2 != value))
				{
					this._PhoneNumber2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this._STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY2", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CITY2
		{
			get
			{
				return this._CITY2;
			}
			set
			{
				if ((this._CITY2 != value))
				{
					this._CITY2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ZIP
		{
			get
			{
				return this._ZIP;
			}
			set
			{
				if ((this._ZIP != value))
				{
					this._ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditDays", DbType="Int")]
		public System.Nullable<int> CreditDays
		{
			get
			{
				return this._CreditDays;
			}
			set
			{
				if ((this._CreditDays != value))
				{
					this._CreditDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCE", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string SOURCE
		{
			get
			{
				return this._SOURCE;
			}
			set
			{
				if ((this._SOURCE != value))
				{
					this._SOURCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingBalance", DbType="Money")]
		public System.Nullable<decimal> ClosingBalance
		{
			get
			{
				return this._ClosingBalance;
			}
			set
			{
				if ((this._ClosingBalance != value))
				{
					this._ClosingBalance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimit", DbType="Money")]
		public System.Nullable<decimal> CreditLimit
		{
			get
			{
				return this._CreditLimit;
			}
			set
			{
				if ((this._CreditLimit != value))
				{
					this._CreditLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Available", DbType="Money")]
		public System.Nullable<decimal> Available
		{
			get
			{
				return this._Available;
			}
			set
			{
				if ((this._Available != value))
				{
					this._Available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceLevel", DbType="SmallInt NOT NULL")]
		public short PriceLevel
		{
			get
			{
				return this._PriceLevel;
			}
			set
			{
				if ((this._PriceLevel != value))
				{
					this._PriceLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(300)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSales", DbType="Money NOT NULL")]
		public decimal TotalSales
		{
			get
			{
				return this._TotalSales;
			}
			set
			{
				if ((this._TotalSales != value))
				{
					this._TotalSales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSavings", DbType="Money NOT NULL")]
		public decimal TotalSavings
		{
			get
			{
				return this._TotalSavings;
			}
			set
			{
				if ((this._TotalSavings != value))
				{
					this._TotalSavings = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalVisits", DbType="Int NOT NULL")]
		public int TotalVisits
		{
			get
			{
				return this._TotalVisits;
			}
			set
			{
				if ((this._TotalVisits != value))
				{
					this._TotalVisits = value;
				}
			}
		}
	}
	
	public partial class spWS_GetCustomersByStoreIDResult
	{
		
		private int _ID;
		
		private string _AccountNumber;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _PhoneNumber1;
		
		private string _PhoneNumber2;
		
		private string _EmailAddress;
		
		private string _STATE;
		
		private string _CITY;
		
		private string _CITY2;
		
		private string _ZIP;
		
		private string _Address;
		
		private System.Nullable<int> _CreditDays;
		
		private string _SOURCE;
		
		private System.Nullable<decimal> _ClosingBalance;
		
		private System.Nullable<decimal> _CreditLimit;
		
		private System.Nullable<decimal> _Available;
		
		private short _PriceLevel;
		
		private string _Notes;
		
		private decimal _TotalSales;
		
		private decimal _TotalSavings;
		
		private int _TotalVisits;
		
		public spWS_GetCustomersByStoreIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this._AccountNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber1", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhoneNumber1
		{
			get
			{
				return this._PhoneNumber1;
			}
			set
			{
				if ((this._PhoneNumber1 != value))
				{
					this._PhoneNumber1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber2", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhoneNumber2
		{
			get
			{
				return this._PhoneNumber2;
			}
			set
			{
				if ((this._PhoneNumber2 != value))
				{
					this._PhoneNumber2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this._STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY2", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CITY2
		{
			get
			{
				return this._CITY2;
			}
			set
			{
				if ((this._CITY2 != value))
				{
					this._CITY2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ZIP
		{
			get
			{
				return this._ZIP;
			}
			set
			{
				if ((this._ZIP != value))
				{
					this._ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditDays", DbType="Int")]
		public System.Nullable<int> CreditDays
		{
			get
			{
				return this._CreditDays;
			}
			set
			{
				if ((this._CreditDays != value))
				{
					this._CreditDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCE", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string SOURCE
		{
			get
			{
				return this._SOURCE;
			}
			set
			{
				if ((this._SOURCE != value))
				{
					this._SOURCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingBalance", DbType="Money")]
		public System.Nullable<decimal> ClosingBalance
		{
			get
			{
				return this._ClosingBalance;
			}
			set
			{
				if ((this._ClosingBalance != value))
				{
					this._ClosingBalance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimit", DbType="Money")]
		public System.Nullable<decimal> CreditLimit
		{
			get
			{
				return this._CreditLimit;
			}
			set
			{
				if ((this._CreditLimit != value))
				{
					this._CreditLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Available", DbType="Money")]
		public System.Nullable<decimal> Available
		{
			get
			{
				return this._Available;
			}
			set
			{
				if ((this._Available != value))
				{
					this._Available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceLevel", DbType="SmallInt NOT NULL")]
		public short PriceLevel
		{
			get
			{
				return this._PriceLevel;
			}
			set
			{
				if ((this._PriceLevel != value))
				{
					this._PriceLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(300)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSales", DbType="Money NOT NULL")]
		public decimal TotalSales
		{
			get
			{
				return this._TotalSales;
			}
			set
			{
				if ((this._TotalSales != value))
				{
					this._TotalSales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSavings", DbType="Money NOT NULL")]
		public decimal TotalSavings
		{
			get
			{
				return this._TotalSavings;
			}
			set
			{
				if ((this._TotalSavings != value))
				{
					this._TotalSavings = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalVisits", DbType="Int NOT NULL")]
		public int TotalVisits
		{
			get
			{
				return this._TotalVisits;
			}
			set
			{
				if ((this._TotalVisits != value))
				{
					this._TotalVisits = value;
				}
			}
		}
	}
	
	public partial class spWS_GetCustomersbyCriteriaResult
	{
		
		private int _ID;
		
		private string _AccountNumber;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _PhoneNumber1;
		
		private string _PhoneNumber2;
		
		private string _EmailAddress;
		
		private string _STATE;
		
		private string _CITY;
		
		private string _CITY2;
		
		private string _ZIP;
		
		private string _Address;
		
		private System.Nullable<int> _CreditDays;
		
		private string _SOURCE;
		
		private System.Nullable<decimal> _ClosingBalance;
		
		private System.Nullable<decimal> _CreditLimit;
		
		private System.Nullable<decimal> _Available;
		
		private short _PriceLevel;
		
		private string _Notes;
		
		private decimal _TotalSales;
		
		private decimal _TotalSavings;
		
		private int _TotalVisits;
		
		public spWS_GetCustomersbyCriteriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this._AccountNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber1", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhoneNumber1
		{
			get
			{
				return this._PhoneNumber1;
			}
			set
			{
				if ((this._PhoneNumber1 != value))
				{
					this._PhoneNumber1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber2", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhoneNumber2
		{
			get
			{
				return this._PhoneNumber2;
			}
			set
			{
				if ((this._PhoneNumber2 != value))
				{
					this._PhoneNumber2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this._STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY2", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CITY2
		{
			get
			{
				return this._CITY2;
			}
			set
			{
				if ((this._CITY2 != value))
				{
					this._CITY2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ZIP
		{
			get
			{
				return this._ZIP;
			}
			set
			{
				if ((this._ZIP != value))
				{
					this._ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditDays", DbType="Int")]
		public System.Nullable<int> CreditDays
		{
			get
			{
				return this._CreditDays;
			}
			set
			{
				if ((this._CreditDays != value))
				{
					this._CreditDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCE", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string SOURCE
		{
			get
			{
				return this._SOURCE;
			}
			set
			{
				if ((this._SOURCE != value))
				{
					this._SOURCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingBalance", DbType="Money")]
		public System.Nullable<decimal> ClosingBalance
		{
			get
			{
				return this._ClosingBalance;
			}
			set
			{
				if ((this._ClosingBalance != value))
				{
					this._ClosingBalance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimit", DbType="Money")]
		public System.Nullable<decimal> CreditLimit
		{
			get
			{
				return this._CreditLimit;
			}
			set
			{
				if ((this._CreditLimit != value))
				{
					this._CreditLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Available", DbType="Money")]
		public System.Nullable<decimal> Available
		{
			get
			{
				return this._Available;
			}
			set
			{
				if ((this._Available != value))
				{
					this._Available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceLevel", DbType="SmallInt NOT NULL")]
		public short PriceLevel
		{
			get
			{
				return this._PriceLevel;
			}
			set
			{
				if ((this._PriceLevel != value))
				{
					this._PriceLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(300)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSales", DbType="Money NOT NULL")]
		public decimal TotalSales
		{
			get
			{
				return this._TotalSales;
			}
			set
			{
				if ((this._TotalSales != value))
				{
					this._TotalSales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSavings", DbType="Money NOT NULL")]
		public decimal TotalSavings
		{
			get
			{
				return this._TotalSavings;
			}
			set
			{
				if ((this._TotalSavings != value))
				{
					this._TotalSavings = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalVisits", DbType="Int NOT NULL")]
		public int TotalVisits
		{
			get
			{
				return this._TotalVisits;
			}
			set
			{
				if ((this._TotalVisits != value))
				{
					this._TotalVisits = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
